unit uTestDatabaseConfig;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, uDatabaseConfig, IniFiles;

type
  // Test methods for class TDatabaseConfig

  TestTDatabaseConfig = class(TTestCase)
  strict private
    FDatabaseConfig: TDatabaseConfig;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure Test1;
  end;

implementation

procedure TestTDatabaseConfig.SetUp;
begin
  FDatabaseConfig := TDatabaseConfig.Create('../cfg/wk.ini');
end;

procedure TestTDatabaseConfig.TearDown;
begin
  FDatabaseConfig.Free;
  FDatabaseConfig := nil;
end;

procedure TestTDatabaseConfig.Test1;
begin
  FDatabaseConfig.Database := 'wk';
  FDatabaseConfig.Host := '192.168.122.14';
  FDatabaseConfig.Port := 3306;
  FDatabaseConfig.User := 'root';
  FDatabaseConfig.Password := 'temp';
  CheckEquals('wk', FDatabaseConfig.Database);
  CheckEquals('192.168.122.14', FDatabaseConfig.Host);
  CheckEquals(3306, FDatabaseConfig.Port);
  CheckEquals('root', FDatabaseConfig.User);
  CheckEquals('temp', FDatabaseConfig.Password);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDatabaseConfig.Suite);
end.

